/**
 * PCR Staff App 2.10.1 — Kitchen order summaries by date (hotfix). 3.0.0: the save follows the dinner_cutoff setting
 * (default 11:55pm) and is re-saved after the late-request close (default 12pm) — see Release3.gs mealTick.
 *
 * - The Kitchen page can open the dinner order summary / prep list (plus breakfast & lunch headcounts) for the last
 *   3 days, today and tomorrow (getKitchenDaySummary). Read only: past dates never run the approval workflow.
 * - Source for a dinner date: the saved snapshot in the existing "Dinner Prep Snapshots" tab (2.10.0 already upserts it
 *   after 8:30pm; 2.10.1 also saves it at the 8:00pm cutoff and stores a compact, size-safe payload), else it is
 *   built live from the Dinner Orders rows (so it works even when no snapshot exists).
 * - Automatic save at the 8pm Fiji cutoff:
 *     a) time-driven trigger dinnerSummaryTick ~8:10pm Fiji (installDinnerSummaryTrigger, needs script.scriptapp), and
 *     b) fallback: the first app request after 8:00pm Fiji saves it (no extra permission needed; once per night).
 *   Each save also writes a PDF into the Drive folder "PCR Kitchen Order Summaries" when the Drive scope is authorised
 *   (otherwise the Kitchen page builds the PDF in the browser from the same data).
 * - setupDinnerSummaries(): run ONCE from the Apps Script editor → authorises Drive + triggers, installs the trigger and
 *   backfills snapshots/PDFs for the last 3 days + tomorrow.
 */
var DSUM_FOLDER_NAME = 'PCR Kitchen Order Summaries';
var DSUM_SHEET = 'Dinner Prep Snapshots';
var DSUM_HEADERS = ['id', 'serviceDate', 'generatedAt', 'autoGenerated', 'totalOrders', 'payloadJson',
  'payloadJson2', 'payloadJson3', 'payloadJson4', 'kind', 'generatedBy', 'pdfFileId', 'pdfUrl', 'pdfAt'];
var DSUM_CELL = 45000;          // Sheets cell limit is 50,000 chars
var DSUM_DAYS_BACK = 3;         // picker: last 3 days + today + tomorrow
var DSUM_CUTOFF_HOUR = 20;      // dinner cutoff 8:00pm Fiji

function dsumDate(v) { var m = String(v == null ? '' : v).match(/(\d{4}-\d{2}-\d{2})/); return m ? m[1] : ''; }

/** Compact order row kept in a snapshot (enough to rebuild the prep list / print exactly). */
function dsumCompact(o) {
  return { i: o.id, e: String(o.userEmail || '').toLowerCase(), u: o.userName || '', n: o.displayName || o.userName || '',
    d: o.department || '', m: o.mealChoice || '', t: o.createdAt || '', s: String(o.status || ''), l: truthy(o.late) ? 1 : 0,
    sn: o.specialNote || '' };
}
function dsumExpand(c, serviceDate) {
  var note = cleanSpecialNote(c.sn);
  return { id: c.i, serviceDate: serviceDate, userEmail: c.e, userName: c.u, displayName: c.n, department: c.d,
    mealChoice: c.m, createdAt: c.t, status: c.s, late: !!c.l, specialNote: note, noteFlag: noteFlag(note) };
}

/** Dinner order rows for a service date (not cancelled / rejected), decorated with notes + preferred names. */
function dsumDinnerRows(serviceDate, nameMap) {
  var orders = sheetToObjects('Dinner Orders').filter(function (o) {
    return dsumDate(o.serviceDate) === serviceDate && o.status !== 'cancelled' && o.status !== 'rejected' && o.status !== 'special_pending';
  });
  decorateOrderNotes(orders, nameMap || preferredNameMap());
  return orders;
}

/** Same shape as buildPrepPayload (Code.gs) but from already-decorated order objects. */
function dsumPrepFromOrders(serviceDate, orders) {
  var nameMap = {};
  orders.forEach(function (o) { if (o.userEmail) nameMap[String(o.userEmail).toLowerCase()] = o.displayName || o.userName; });
  var tally = {};
  orders.forEach(function (o) { var k = o.mealChoice || 'Standard'; tally[k] = (tally[k] || 0) + 1; });
  var byItem = {};
  Object.keys(tally).sort().forEach(function (k) { byItem[k] = []; });
  orders.forEach(function (o) {
    var k = o.mealChoice || 'Standard';
    byItem[k].push({ id: o.id, userName: o.userName, displayName: o.displayName, department: o.department,
      foodSelection: o.mealChoice || k, orderedAt: o.createdAt, comments: o.specialNote || '', specialNote: o.specialNote || '',
      noteFlag: o.noteFlag || '', status: o.status,
      approved: o.status === 'approved' || o.status === 'late_approved' || o.status === 'prepared' || o.status === 'served',
      denied: o.status === 'rejected' || o.status === 'cancelled', late: truthy(o.late), servedCheck: '' });
  });
  function cnt(f) { return orders.filter(f).length; }
  return flagOffMenu({
    serviceDate: serviceDate,
    totalOrders: orders.length,
    tally: tally,
    byItem: byItem,
    pending: cnt(function (o) { return o.status === 'pending' || o.status === 'late_pending'; }),
    approved: cnt(function (o) { return o.status === 'approved' || o.status === 'late_approved' || o.status === 'prepared' || o.status === 'served'; }),
    late: cnt(function (o) { return truthy(o.late); }),
    specialNotes: kitchenNoteEntries('dinner', orders, nameMap),
    orders: orders
  });
}

/** payloadJson(+2..4) text for a snapshot row: compact v2 format, split across cells so it never hits the 50k limit. */
function dsumPayloadCells(serviceDate, orders) {
  var json = JSON.stringify({ v: 2, serviceDate: serviceDate, orders: orders.map(dsumCompact) });
  var cells = [];
  for (var i = 0; i < 4; i++) cells.push(json.substring(i * DSUM_CELL, (i + 1) * DSUM_CELL));
  if (json.length > 4 * DSUM_CELL) throw new Error('Snapshot too large');
  return cells;
}

/** Parses a snapshot row (v2 compact, or the 2.10.0 full payload) → prep payload, or null if unreadable. */
function dsumPrepFromSnapshot(s) {
  if (!s) return null;
  var txt = String(s.payloadJson || '') + String(s.payloadJson2 || '') + String(s.payloadJson3 || '') + String(s.payloadJson4 || '');
  if (!txt) return null;
  var obj;
  try { obj = JSON.parse(txt); } catch (e) { return null; }
  var date = dsumDate(s.serviceDate);
  if (obj && obj.v === 2 && Array.isArray(obj.orders)) {
    return dsumPrepFromOrders(date, obj.orders.map(function (c) { return dsumExpand(c, date); }));
  }
  if (obj && obj.tally && obj.byItem) return obj; // 2.10.0 format
  return null;
}

function dsumSnapshotRow(serviceDate) {
  var rows = [];
  try { rows = sheetToObjects(DSUM_SHEET); } catch (e) { rows = []; }
  var m = rows.filter(function (s) { return dsumDate(s.serviceDate) === serviceDate; });
  return m.length ? m[m.length - 1] : null;
}
function dsumSnapMeta(s) {
  if (!s) return null;
  return { id: s.id, serviceDate: dsumDate(s.serviceDate), generatedAt: s.generatedAt || '', autoGenerated: truthy(s.autoGenerated),
    totalOrders: Number(s.totalOrders || 0), kind: s.kind || (truthy(s.autoGenerated) ? 'auto' : ''), generatedBy: s.generatedBy || '',
    pdfFileId: s.pdfFileId || '', pdfUrl: s.pdfUrl || '', pdfAt: s.pdfAt || '' };
}

/**
 * Saves (insert or update) the snapshot for a dinner date from the order rows. Used by the 8pm tick, the 2.10.0 8:30pm
 * upsert (upsertDinnerPrepSnapshot) and the backfill. Returns the row object.
 */
function dsumSaveSnapshot(serviceDate, autoGenerated, kind, by) {
  var sh = ensureSheet(getSS(), DSUM_SHEET, DSUM_HEADERS);
  var orders = dsumDinnerRows(serviceDate);
  var cells = dsumPayloadCells(serviceDate, orders);
  var existing = dsumSnapshotRow(serviceDate);
  var row = {
    id: existing ? existing.id : uid('dprep'),
    serviceDate: serviceDate,
    generatedAt: nowIso(),
    autoGenerated: !!autoGenerated,
    totalOrders: orders.length,
    payloadJson: cells[0], payloadJson2: cells[1], payloadJson3: cells[2], payloadJson4: cells[3],
    kind: kind || (autoGenerated ? 'auto' : 'manual'),
    generatedBy: by || ''
  };
  if (existing) {
    var patch = {};
    ['generatedAt', 'autoGenerated', 'totalOrders', 'payloadJson', 'payloadJson2', 'payloadJson3', 'payloadJson4', 'kind', 'generatedBy']
      .forEach(function (k) { patch[k] = row[k]; });
    updateRowById(DSUM_SHEET, existing.id, patch);
    row.pdfFileId = existing.pdfFileId || ''; row.pdfUrl = existing.pdfUrl || ''; row.pdfAt = existing.pdfAt || '';
  } else {
    appendRow(DSUM_SHEET, row, DSUM_HEADERS);
  }
  return row;
}

/* ---------- PDF (Drive) ---------- */
function dsumEsc(s) {
  return String(s == null ? '' : s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}
function dsumNoteHtml(note) {
  note = cleanSpecialNote(note);
  if (!note) return '';
  var f = noteFlag(note);
  var st = f === 'allergy' ? 'color:#b91c1c;font-weight:700' : (f === 'diet' ? 'color:#b45309;font-weight:600' : 'color:#111');
  var lbl = f === 'allergy' ? 'ALLERGY' : (f === 'diet' ? 'DIET' : '');
  return '<span style="' + st + '">' + (lbl ? '&#9888; ' + lbl + ': ' : '') + dsumEsc(note) + '</span>';
}
/** Printable dinner prep list — same layout as the Kitchen page "Dinner Prep List" (frontend buildPrepHtml). */
function dsumPrepHtml(serviceDate, prep, meta) {
  prep = prep || {};
  var tally = prep.tally || {}, byItem = prep.byItem || {};
  var notes = prep.specialNotes || [];
  var nA = notes.filter(function (e) { return e.flag === 'allergy'; }).length;
  var h = '<div style="font-family:Arial,sans-serif;color:#111;max-width:760px;margin:0 auto;padding:8px">';
  h += '<div style="text-align:center"><h1 style="margin:4px 0;font-size:20px">Paradise Cove Resort — Dinner Prep List — ' + dsumEsc(serviceDate) + ' FJT</h1>';
  h += '<p style="font-size:11px;color:#555;margin:2px 0">' + dsumEsc(meta || '') + '</p>';
  h += '<p>Total dinner orders: <strong>' + (prep.totalOrders || 0) + '</strong></p></div>';
  h += '<div style="margin:10px 0;padding:8px;border:2px solid ' + (notes.length ? '#b91c1c' : '#ddd') + '"><h2 style="margin:0 0 6px;font-size:15px;color:#b91c1c">&#9888; Allergies &amp; special requests</h2>';
  if (!notes.length) h += '<p style="margin:0;font-size:12px;color:#555">None for this service.</p>';
  else {
    h += '<p style="margin:0 0 6px;font-size:11px">' + notes.length + ' note(s)' + (nA ? ' · <strong style="color:#b91c1c">' + nA + ' allergy</strong>' : '') + ' · check before plating</p>';
    h += '<table style="width:100%;border-collapse:collapse;font-size:12px" border="1" cellpadding="4"><tr><th>Flag</th><th>Staff</th><th>Dish</th><th>Note</th></tr>';
    notes.forEach(function (e) {
      var bg = e.flag === 'allergy' ? '#fee2e2' : (e.flag === 'diet' ? '#fef3c7' : '#fff');
      h += '<tr style="background:' + bg + '"><td><strong>' + (e.flag === 'request' ? 'Request' : '&#9888; ' + (e.flag === 'allergy' ? 'ALLERGY' : 'DIET')) + '</strong></td><td><strong>' + dsumEsc(e.name) + '</strong><br/><span style="font-size:10px">' + dsumEsc(e.department) + '</span></td><td>' + dsumEsc(e.dish) + '</td><td>' + dsumEsc(e.note) + '</td></tr>';
    });
    h += '</table>';
  }
  h += '</div>';
  var off = prep.offMenu || [];
  if (off.length) {
    h += '<div style="margin:10px 0;padding:8px;border:2px solid #d97706;background:#fffbeb"><h2 style="margin:0 0 6px;font-size:14px;color:#b45309">&#9888; Not on this day\'s menu (' + off.length + ') — check with the staff member</h2><ul style="margin:0;font-size:12px">';
    off.forEach(function (o) { h += '<li><strong>' + dsumEsc(o.name) + '</strong> (' + dsumEsc(o.department) + ') — ' + dsumEsc(o.dish) + '</li>'; });
    h += '</ul></div>';
  }
  var spm = (typeof s34SpecialFor === 'function') ? s34SpecialFor(serviceDate).dinner : [];
  if (spm.length) {
    h += '<div style="margin:10px 0;padding:8px;border:2px solid #0d9488"><h2 style="margin:0 0 6px;font-size:14px;color:#0f766e">Special meal requests (' + spm.length + ', approved by HOD)</h2><ul style="margin:0;font-size:12px">';
    spm.forEach(function (o) { h += '<li><strong>' + dsumEsc(o.name) + '</strong> (' + dsumEsc(o.department) + ') — ' + dsumEsc(o.reason) + '</li>'; });
    h += '</ul></div>';
  }
  h += '<h2 style="font-size:14px;margin-top:14px">Breakdown (sorted by food)</h2>';
  Object.keys(tally).sort().forEach(function (k) {
    var offK = (prep.menu || []).length && !(prep.menu || []).some(function (n) { return String(n).trim().toLowerCase() === String(k).trim().toLowerCase(); });
    h += '<div style="margin:4px 0;padding:4px 0;border-bottom:1px solid #ddd"><strong>' + dsumEsc(k) + '</strong>' + (offK ? ' <span style="color:#b45309">(NOT ON MENU)</span>' : '') + ': ' + tally[k] + ' &nbsp; Given out: ______</div>';
  });
  Object.keys(byItem).sort().forEach(function (k) {
    var list = byItem[k] || [];
    h += '<h3 style="margin-top:16px">' + dsumEsc(k) + ' (' + list.length + ')</h3><table style="width:100%;border-collapse:collapse;font-size:11px" border="1" cellpadding="3">' +
      '<tr><th>Served</th><th>Staff name</th><th>Dept</th><th>Time ordered</th><th>Special note / allergy</th><th>Status</th></tr>';
    list.forEach(function (o) {
      h += '<tr><td>&#9744;</td><td>' + dsumEsc(o.displayName || o.userName) + '</td><td>' + dsumEsc(o.department) + '</td><td>' + dsumEsc(o.orderedAt) + '</td><td>' +
        dsumNoteHtml(o.specialNote) + '</td><td>' + (o.approved ? 'APPROVED' : dsumEsc(o.status)) + (o.late ? ' LATE' : '') + '</td></tr>';
    });
    h += '</table>';
  });
  h += '<div style="margin-top:20px;padding:10px;border:1px dashed #888"><strong>Did not order but received dinner</strong><br/><br/>Name __________ Item __________ Time ______<br/><br/>Name __________ Item __________ Time ______</div>';
  h += '<div style="margin-top:24px;font-size:13px">Signature Chef in charge __________ &nbsp; HOD __________ &nbsp; Date ______</div></div>';
  return h;
}
function dsumFolder() {
  var it = DriveApp.getFoldersByName(DSUM_FOLDER_NAME);
  return it.hasNext() ? it.next() : DriveApp.createFolder(DSUM_FOLDER_NAME);
}
/** Writes/replaces the Drive PDF for a snapshot row. Throws if the Drive scope is not authorised. */
function dsumWritePdf(row) {
  var date = dsumDate(row.serviceDate);
  var prep = dsumPrepFromSnapshot(row) || dsumPrepFromOrders(date, dsumDinnerRows(date));
  var meta = 'Saved ' + (row.generatedAt || nowIso()) + (row.generatedBy ? ' · ' + row.generatedBy : '');
  var html = '<html><head><meta charset="utf-8"></head><body>' + dsumPrepHtml(date, prep, meta) + '</body></html>';
  var blob = HtmlService.createHtmlOutput(html).getBlob().getAs('application/pdf').setName('Dinner order summary ' + date + '.pdf');
  var folder = dsumFolder();
  if (row.pdfFileId) { try { DriveApp.getFileById(row.pdfFileId).setTrashed(true); } catch (e) {} }
  var file = folder.createFile(blob);
  var patch = { pdfFileId: file.getId(), pdfUrl: file.getUrl(), pdfAt: nowIso() };
  updateRowById(DSUM_SHEET, row.id, patch);
  row.pdfFileId = patch.pdfFileId; row.pdfUrl = patch.pdfUrl; row.pdfAt = patch.pdfAt;
  return patch;
}
function dsumTryPdf(row) {
  try { return { ok: true, pdf: dsumWritePdf(row) }; } catch (e) { return { ok: false, error: String((e && e.message) || e) }; }
}

/* ---------- 8pm auto save ---------- */
/** Saves tomorrow's dinner summary (+ PDF when Drive is authorised). Idempotent per night via a script property. */
function dsumAutoSave(by, force) {
  var now = getFijiNow();
  // 3.0.0: the dinner cutoff is an App Setting (dinner_cutoff, default 23:55) — save the latest date whose cutoff passed
  var date = r3LastPassed(now, -1, mealTimes().dinner_cutoff);
  if (force && !date) date = fijiDateString(addFijiDays(now, 1));
  if (!date) return { skipped: 'no dinner cutoff passed yet' };
  var key = 'dsum_saved_' + date;
  var props = PropertiesService.getScriptProperties();
  var done = props.getProperty(key);
  if (done && !force) return { skipped: 'already saved', serviceDate: date, at: done };
  var lock = LockService.getScriptLock();
  if (!lock.tryLock(15000)) return { skipped: 'busy' };
  try {
    done = props.getProperty(key);
    if (done && !force) return { skipped: 'already saved', serviceDate: date, at: done };
    var row = dsumSaveSnapshot(date, true, 'auto', by || 'auto 8pm cutoff');
    var pdf = dsumTryPdf(row);
    props.setProperty(key, nowIso() + (pdf.ok ? ' +pdf' : ''));
    try { CacheService.getScriptCache().put('dsum_ok_' + date, '1', 21600); } catch (e) {}
    // tidy old keys (keep ~2 weeks)
    try {
      var all = props.getKeys(), oldest = fijiDateString(addFijiDays(now, -14));
      all.forEach(function (k) { if (k.indexOf('dsum_saved_') === 0 && k.substring(11) < oldest) props.deleteProperty(k); });
    } catch (e2) {}
    return { saved: true, serviceDate: date, totalOrders: row.totalOrders, pdf: pdf };
  } finally { lock.releaseLock(); }
}
/** Cheap check run before normal requests: after 8pm, the first request of the night saves the summary. Never throws. */
function dsumMaybeAutoSave() {
  // 3.0.0: cutoff save + late-window auto-approval + final re-save (Release3.gs mealTick; lazy, cached)
  mealTickSafe();
}
/** Time-driven trigger target (~8:10pm Fiji). Runs the usual approval waves first, then saves. */
function dinnerSummaryTick() {
  try { processDinnerWorkflow({}); } catch (e) {}
  var r = mealTick(false);
  if (typeof a33Flush === 'function') { try { a33Flush(); } catch (e) {} } // 3.2.0: phone notifications from the tick
  return r;
}
function installDinnerSummaryTrigger() {
  ScriptApp.getProjectTriggers().forEach(function (t) {
    if (t.getHandlerFunction() === 'dinnerSummaryTick') ScriptApp.deleteTrigger(t);
  });
  ScriptApp.newTrigger('dinnerSummaryTick').timeBased().everyHours(1).create(); // 3.0.0: hourly (cutoff / late close are settings)
  return listDinnerSummaryTriggers();
}
function listDinnerSummaryTriggers() {
  return ScriptApp.getProjectTriggers().map(function (t) { return t.getHandlerFunction() + ' (' + t.getEventType() + ')'; });
}
/** Backfill: makes sure the last N days + today + tomorrow have a snapshot (built from order rows) and a Drive PDF. */
function dsumBackfill(daysBack, withPdf) {
  var now = getFijiNow(), out = [];
  for (var i = -(daysBack || DSUM_DAYS_BACK); i <= 0; i++) {
    var date = fijiDateString(addFijiDays(now, i));
    var s = dsumSnapshotRow(date);
    var prep = dsumPrepFromSnapshot(s);
    var liveN = dsumDinnerRows(date).length;
    var r = { serviceDate: date, liveOrders: liveN };
    if (!s || !prep || Number(prep.totalOrders || 0) === 0 && liveN > 0) {
      if (liveN === 0 && !s) { r.skipped = 'no orders'; out.push(r); continue; }
      s = dsumSaveSnapshot(date, false, 'backfill', 'backfill from order rows ' + nowIso());
      r.saved = true;
    } else r.kept = s.generatedAt;
    r.totalOrders = Number(s.totalOrders || 0);
    if (withPdf && !s.pdfFileId) r.pdf = dsumTryPdf(s);
    else if (s.pdfFileId) r.pdfUrl = s.pdfUrl;
    out.push(r);
  }
  return out;
}
/**
 * RUN ONCE from the Apps Script editor (Run ▸ setupDinnerSummaries). Google shows a consent screen for Drive + triggers
 * the first time. Installs the ~8:10pm trigger and backfills snapshots + PDFs for the last 3 days.
 */
function setupDinnerSummaries() {
  var res = { trigger: installDinnerSummaryTrigger(), backfill: dsumBackfill(DSUM_DAYS_BACK, true), folder: dsumFolder().getUrl() };
  Logger.log(JSON.stringify(res, null, 2));
  return res;
}

/* ---------- API ---------- */
function dsumDays(now) {
  now = now || getFijiNow();
  var counts = {};
  sheetToObjects('Dinner Orders').forEach(function (o) {
    if (o.status === 'cancelled' || o.status === 'rejected') return;
    var d = dsumDate(o.serviceDate); counts[d] = (counts[d] || 0) + 1;
  });
  var snaps = {};
  try { sheetToObjects(DSUM_SHEET).forEach(function (s) { snaps[dsumDate(s.serviceDate)] = s; }); } catch (e) {}
  var today = fijiDateString(now), days = [];
  for (var i = -DSUM_DAYS_BACK; i <= 1; i++) {
    var d = fijiDateString(addFijiDays(now, i));
    var s = snaps[d];
    days.push({ date: d, offset: i, isToday: d === today, dinnerOrders: counts[d] || 0, saved: !!s,
      savedTotal: s ? Number(s.totalOrders || 0) : null, pdfUrl: s ? (s.pdfUrl || '') : '' });
  }
  return days;
}
function dsumHeadcount(meal, serviceDate, nameMap) {
  var sheet = meal === 'breakfast' ? 'Breakfast Orders' : 'Lunch Orders';
  var orders = sheetToObjects(sheet).filter(function (o) { return dsumDate(o.serviceDate) === serviceDate && o.status !== 'cancelled'; });
  decorateOrderNotes(orders, nameMap);
  var counted = meal === 'breakfast' ? orders.filter(countsInBreakfastTotal).length
    : orders.filter(function (o) { return o.status !== 'rejected' && o.status !== 'declined' && o.status !== 'late_pending'; }).length;
  return {
    serviceDate: serviceDate,
    totalCounted: counted,
    orders: orders.map(function (o) {
      return { id: o.id, userName: o.userName, displayName: o.displayName, department: o.department, timeOrdered: o.createdAt,
        status: o.status, late: truthy(o.late), notes: o.notes || '', specialNote: o.specialNote || '', noteFlag: o.noteFlag || '' };
    }),
    specialNotes: kitchenNoteEntries(meal, orders, nameMap)
  };
}
/**
 * GET getKitchenDaySummary&serviceDate=YYYY-MM-DD[&source=rows|snapshot] — chef / HOD / admin / superadmin.
 * Read only (never approves or rewrites anything).
 */
function getKitchenDaySummary(p) {
  try { requireKitchenOrAdmin(p); } catch (e) { return { success: false, error: String(e.message || e) }; }
  var now = getFijiNow();
  var date = dsumDate(p.serviceDate) || fijiDateString(now);
  var nameMap = preferredNameMap();
  var s = dsumSnapshotRow(date);
  var snapPrep = dsumPrepFromSnapshot(s);
  var rows = dsumDinnerRows(date, nameMap);
  var livePrep = dsumPrepFromOrders(date, rows);
  var want = String(p.source || '');
  var useSnap = snapPrep && want !== 'rows';
  var tomorrow = fijiDateString(addFijiDays(now, 1));
  var dinnerOpen = mealPhase('dinner', date, now) === 'open';
  var out = {
    serviceDate: date,
    fijiNow: formatFiji(now),
    days: dsumDays(now),
    dinner: {
      serviceDate: date,
      prep: useSnap ? snapPrep : livePrep,
      source: useSnap ? 'snapshot' : 'rows',
      snapshot: dsumSnapMeta(s),
      snapshotReadable: !!snapPrep,
      liveTotal: livePrep.totalOrders,
      snapshotTotal: snapPrep ? snapPrep.totalOrders : null,
      stillOpen: dinnerOpen,
      autoGeneratedAt830: false
    },
    breakfast: dsumHeadcount('breakfast', date, nameMap),
    lunch: dsumHeadcount('lunch', date, nameMap)
  };
  // 3.4.0: orders vs estimated staff on the island (roster) + approved special meal requests
  if (typeof s34Estimate === 'function') {
    try { out.island = s34Estimate(date); } catch (eI) { out.island = null; }
    var sp = s34SpecialFor(date);
    out.dinner.specialMeals = sp.dinner; out.breakfast.specialMeals = sp.breakfast; out.lunch.specialMeals = sp.lunch;
  }
  if (String(p.compact || '') === '1') { delete out.dinner.prep.orders; }
  return { success: true, data: out };
}
/** GET getSavedSummaryPdf&serviceDate= — the Drive PDF as base64 (chef / admin). */
function getSavedSummaryPdf(p) {
  try { requireKitchenOrAdmin(p); } catch (e) { return { success: false, error: String(e.message || e) }; }
  var s = dsumSnapshotRow(dsumDate(p.serviceDate));
  if (!s || !s.pdfFileId) return { success: false, error: 'No saved PDF for this date yet' };
  try {
    var f = DriveApp.getFileById(s.pdfFileId);
    return { success: true, data: { name: f.getName(), url: s.pdfUrl, base64: Utilities.base64Encode(f.getBlob().getBytes()) } };
  } catch (e) { return { success: false, error: 'Saved PDF not readable: ' + String((e && e.message) || e) }; }
}
/** GET saveDinnerSummary&serviceDate= — superadmin/admin: save (or re-save) a snapshot now (+PDF when possible). */
function saveDinnerSummary(p) {
  var u = getRequester(p);
  if (!u || !isChefPerm(u)) return { success: false, error: 'Chef / admin only' };
  var date = dsumDate(p.serviceDate);
  if (!date) return { success: false, error: 'serviceDate required' };
  var row = dsumSaveSnapshot(date, false, 'manual', 'saved by ' + u.email);
  var pdf = dsumTryPdf(row);
  return { success: true, data: { snapshot: dsumSnapMeta(row), pdf: pdf } };
}
/** GET backfillDinnerSummaries — superadmin: snapshots (+PDFs when Drive is authorised) for the last 3 days + today. */
function backfillDinnerSummaries(p) {
  var u = getRequester(p);
  if (!u || !isAdminPerm(u)) return { success: false, error: 'Admin only' };
  return { success: true, data: { backfill: dsumBackfill(Number(p.days || DSUM_DAYS_BACK), true) } };
}
/** GET dinnerSummaryStatus — superadmin: trigger + Drive permission check. */
function dinnerSummaryStatus(p) {
  var u = getRequester(p);
  if (!u || !isAdminPerm(u)) return { success: false, error: 'Admin only' };
  var out = { fijiNow: formatFiji(getFijiNow()) };
  try { out.triggers = listDinnerSummaryTriggers(); } catch (e) { out.triggersError = String((e && e.message) || e); }
  try { out.folder = dsumFolder().getUrl(); } catch (e) { out.driveError = String((e && e.message) || e); }
  out.days = dsumDays();
  return { success: true, data: out };
}
